print('#####################################')
print('#                                   #')
print('#     Natalie Grace Katiandagho     #')
print('#           2310817120003           #')
print('#                                   #')
print('#####################################')
